---
version: "3.7"

services:
  time_machine:
    image: msjpq/time-machine
    container_name: time-machine
    restart: unless-stopped
    network_mode: host
    volumes:
      - <FULL_BACKUPS_PATH_HERE>:/share
    environment:
      - SMB_USER=<USERNAME_HERE>
      - SMB_PASSWORD=<PASSWORD_HERE>